{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "57b3b217",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "KeysView(environ({'ALLUSERSPROFILE': 'C:\\\\ProgramData', 'APPDATA': 'C:\\\\Users\\\\lenovo\\\\AppData\\\\Roaming', 'CHOCOLATEYINSTALL': 'C:\\\\ProgramData\\\\chocolatey', 'CHOCOLATEYLASTPATHUPDATE': '132630958274327839', 'COMMONPROGRAMFILES': 'C:\\\\Program Files\\\\Common Files', 'COMMONPROGRAMFILES(X86)': 'C:\\\\Program Files (x86)\\\\Common Files', 'COMMONPROGRAMW6432': 'C:\\\\Program Files\\\\Common Files', 'COMPUTERNAME': 'LAPTOP-EVI9LEN4', 'COMSPEC': 'C:\\\\WINDOWS\\\\system32\\\\cmd.exe', 'CONDA_DEFAULT_ENV': 'C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env', 'CONDA_EXE': 'C:\\\\Users\\\\lenovo\\\\miniconda3\\\\Scripts\\\\conda.exe', 'CONDA_PREFIX': 'C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env', 'CONDA_PREFIX_1': 'C:\\\\Users\\\\lenovo\\\\miniconda3', 'CONDA_PROMPT_MODIFIER': '(C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env) ', 'CONDA_PYTHON_EXE': 'C:\\\\Users\\\\lenovo\\\\miniconda3\\\\python.exe', 'CONDA_SHLVL': '2', 'DRIVERDATA': 'C:\\\\Windows\\\\System32\\\\Drivers\\\\DriverData', 'FPS_BROWSER_APP_PROFILE_STRING': 'Internet Explorer', 'FPS_BROWSER_USER_PROFILE_STRING': 'Default', 'HOMEDRIVE': 'C:', 'HOMEPATH': '\\\\Users\\\\lenovo', 'INTELLIJ IDEA COMMUNITY EDITION': 'C:\\\\Program Files\\\\JetBrains\\\\IntelliJ IDEA Community Edition 2021.1\\\\bin;', 'LOCALAPPDATA': 'C:\\\\Users\\\\lenovo\\\\AppData\\\\Local', 'LOGONSERVER': '\\\\\\\\LAPTOP-EVI9LEN4', 'NUMBER_OF_PROCESSORS': '8', 'ONEDRIVE': 'C:\\\\Users\\\\lenovo\\\\OneDrive', 'OS': 'Windows_NT', 'PATH': 'C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env;C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env\\\\Library\\\\mingw-w64\\\\bin;C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env\\\\Library\\\\usr\\\\bin;C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env\\\\Library\\\\bin;C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env\\\\Scripts;C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env\\\\bin;C:\\\\Users\\\\lenovo\\\\miniconda3\\\\condabin;C:\\\\Program Files (x86)\\\\VMware\\\\VMware Player\\\\bin;C:\\\\Program Files\\\\Common Files\\\\Oracle\\\\Java\\\\javapath;C:\\\\WINDOWS\\\\system32;C:\\\\WINDOWS;C:\\\\WINDOWS\\\\System32\\\\Wbem;C:\\\\WINDOWS\\\\System32\\\\WindowsPowerShell\\\\v1.0;C:\\\\WINDOWS\\\\System32\\\\OpenSSH;C:\\\\Program Files\\\\Git\\\\cmd;C:\\\\MinGW\\\\bin;C:\\\\ProgramData\\\\chocolatey\\\\bin;C:\\\\Program Files\\\\nodejs;C:\\\\Program Files (x86)\\\\Microsoft SQL Server\\\\150\\\\DTS\\\\Binn;C:\\\\Program Files\\\\Azure Data Studio\\\\bin;C:\\\\Program Files\\\\Microsoft SQL Server\\\\Client SDK\\\\ODBC\\\\170\\\\Tools\\\\Binn;C:\\\\Program Files (x86)\\\\Microsoft SQL Server\\\\150\\\\Tools\\\\Binn;C:\\\\Program Files\\\\Microsoft SQL Server\\\\150\\\\Tools\\\\Binn;C:\\\\Program Files\\\\Microsoft SQL Server\\\\150\\\\DTS\\\\Binn;C:\\\\Program Files\\\\dotnet;C:\\\\Program Files\\\\Microsoft SQL Server\\\\130\\\\Tools\\\\Binn;C:\\\\Program Files\\\\MySQL\\\\MySQL Server 8.0\\\\bin;C:\\\\Program Files\\\\MySQL\\\\MySQL Shell 8.0\\\\bin;C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\Scripts;C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39;C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Microsoft\\\\WindowsApps;C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code\\\\bin;C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Programs\\\\Microsoft VS Code Insiders\\\\bin;C:\\\\Program Files\\\\Java\\\\jdk-16\\\\bin;C:\\\\Program Files\\\\JetBrains\\\\WebStorm 2021.1\\\\bin;.;C:\\\\Program Files\\\\JetBrains\\\\IntelliJ IDEA Community Edition 2021.1\\\\bin;.;C:\\\\Users\\\\lenovo\\\\AppData\\\\Roaming\\\\npm;C:\\\\Program Files\\\\MongoDB\\\\Server\\\\5.0\\\\bin;C:\\\\Program Files\\\\Azure Data Studio\\\\bin;C:\\\\Users\\\\lenovo\\\\.dotnet\\\\tools;C:\\\\Program Files\\\\heroku\\\\bin', 'PATHEXT': '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC', 'PROCESSOR_ARCHITECTURE': 'AMD64', 'PROCESSOR_IDENTIFIER': 'Intel64 Family 6 Model 140 Stepping 1, GenuineIntel', 'PROCESSOR_LEVEL': '6', 'PROCESSOR_REVISION': '8c01', 'PROGRAMDATA': 'C:\\\\ProgramData', 'PROGRAMFILES': 'C:\\\\Program Files', 'PROGRAMFILES(X86)': 'C:\\\\Program Files (x86)', 'PROGRAMW6432': 'C:\\\\Program Files', 'PROMPT': '(C:\\\\Users\\\\lenovo\\\\Desktop\\\\Geo\\\\Geo\\\\env) $P$G', 'PSMODULEPATH': 'C:\\\\Program Files\\\\WindowsPowerShell\\\\Modules;C:\\\\WINDOWS\\\\system32\\\\WindowsPowerShell\\\\v1.0\\\\Modules;C:\\\\Program Files (x86)\\\\Microsoft SQL Server\\\\150\\\\Tools\\\\PowerShell\\\\Modules\\\\', 'PUBLIC': 'C:\\\\Users\\\\Public', 'SESSIONNAME': 'Console', 'SYSTEMDRIVE': 'C:', 'SYSTEMROOT': 'C:\\\\WINDOWS', 'TEMP': 'C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Temp', 'TMP': 'C:\\\\Users\\\\lenovo\\\\AppData\\\\Local\\\\Temp', 'USERDOMAIN': 'LAPTOP-EVI9LEN4', 'USERDOMAIN_ROAMINGPROFILE': 'LAPTOP-EVI9LEN4', 'USERNAME': 'lenovo', 'USERPROFILE': 'C:\\\\Users\\\\lenovo', 'VBOX_MSI_INSTALL_PATH': 'C:\\\\Program Files\\\\Oracle\\\\VirtualBox\\\\', 'VS160COMCOMNTOOLS': 'C:\\\\Program Files (x86)\\\\Microsoft Visual Studio\\\\2019\\\\Community\\\\Common7\\\\Tools\\\\', 'WEBSTORM': 'C:\\\\Program Files\\\\JetBrains\\\\WebStorm 2021.1\\\\bin;', 'WINDIR': 'C:\\\\WINDOWS', 'ZES_ENABLE_SYSMAN': '1', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'JPY_INTERRUPT_EVENT': '2204', 'IPY_INTERRUPT_EVENT': '2204', 'JPY_PARENT_PID': '2360', 'TERM': 'xterm-color', 'CLICOLOR': '1', 'PAGER': 'cat', 'GIT_PAGER': 'cat', 'MPLBACKEND': 'module://matplotlib_inline.backend_inline', 'KMP_DUPLICATE_LIB_OK': 'True', 'KMP_INIT_AT_FORK': 'FALSE'}))"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import json  \n",
    "import pandas as pd  \n",
    "from pandas.io.json import json_normalize  \n",
    "import requests\n",
    "from tabulate import tabulate\n",
    "from sklearn.cluster import KMeans\n",
    "import random\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import folium\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "import os\n",
    "os.environ.keys()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "2ebef561",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>id</th>\n",
       "      <th>language</th>\n",
       "      <th>ontologyId</th>\n",
       "      <th>resultType</th>\n",
       "      <th>access</th>\n",
       "      <th>distance</th>\n",
       "      <th>categories</th>\n",
       "      <th>address.label</th>\n",
       "      <th>address.countryCode</th>\n",
       "      <th>...</th>\n",
       "      <th>address.county</th>\n",
       "      <th>address.city</th>\n",
       "      <th>address.district</th>\n",
       "      <th>address.street</th>\n",
       "      <th>address.postalCode</th>\n",
       "      <th>position.lat</th>\n",
       "      <th>position.lng</th>\n",
       "      <th>contacts</th>\n",
       "      <th>address.subdistrict</th>\n",
       "      <th>address.houseNumber</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Dharamraj</td>\n",
       "      <td>here:pds:place:356te7ug-aab7da0959a549568e2d53...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.12545, 'lng': 72.91935}]</td>\n",
       "      <td>1086</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Dharamraj, Hare Krishna Road, Powai, Mumbai 40...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Powai</td>\n",
       "      <td>Hare Krishna Road</td>\n",
       "      <td>400076</td>\n",
       "      <td>19.12548</td>\n",
       "      <td>72.91935</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Pajasa Apartments</td>\n",
       "      <td>here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.12339, 'lng': 72.91275}]</td>\n",
       "      <td>1115</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Pajasa Apartments, Central Avenue, Hiranandani...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Powai</td>\n",
       "      <td>Central Avenue</td>\n",
       "      <td>400076</td>\n",
       "      <td>19.12339</td>\n",
       "      <td>72.91274</td>\n",
       "      <td>[{'phone': [{'value': '+912269999891'}], 'www'...</td>\n",
       "      <td>Hiranandani Gardens</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Scorpio House</td>\n",
       "      <td>here:pds:place:356te7ug-3fc1a164b55c7471dfef61...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.11933, 'lng': 72.91227}]</td>\n",
       "      <td>1568</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Scorpio House, Central Avenue, Hiranandani Gar...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Powai</td>\n",
       "      <td>Central Avenue</td>\n",
       "      <td>400076</td>\n",
       "      <td>19.11933</td>\n",
       "      <td>72.91227</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Hiranandani Gardens</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Andheri East Service Apartments</td>\n",
       "      <td>here:pds:place:356te7uf-0d5db6077151dcd2369691...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.11747, 'lng': 72.88374}]</td>\n",
       "      <td>3576</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Andheri East Service Apartments, Marol, Andher...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Andheri East</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400059</td>\n",
       "      <td>19.11746</td>\n",
       "      <td>72.88374</td>\n",
       "      <td>[{'phone': [{'value': '+919820049408'}], 'www'...</td>\n",
       "      <td>Marol</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Aghadi Nagar CHS</td>\n",
       "      <td>here:pds:place:356te7v5-ea19989e14a440f9b83865...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.16289, 'lng': 72.93287}]</td>\n",
       "      <td>3860</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Aghadi Nagar CHS, Dargah Road, Bhandup West, M...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Bhandup West</td>\n",
       "      <td>Dargah Road</td>\n",
       "      <td>400078</td>\n",
       "      <td>19.16278</td>\n",
       "      <td>72.93287</td>\n",
       "      <td>[{'mobile': [{'value': '+919324060902'}]}]</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Irel Officers Apartment</td>\n",
       "      <td>here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.09585, 'lng': 72.91369}]</td>\n",
       "      <td>4170</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Irel Officers Apartment, Damodar Park Road, Da...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Ghatkopar West</td>\n",
       "      <td>Damodar Park Road</td>\n",
       "      <td>400086</td>\n",
       "      <td>19.09590</td>\n",
       "      <td>72.91356</td>\n",
       "      <td>[{'phone': [{'value': '+912224220843'}]}]</td>\n",
       "      <td>Damodar Park</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Vic Mon B Wing</td>\n",
       "      <td>here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.11162, 'lng': 72.87512}]</td>\n",
       "      <td>4689</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Vic Mon B Wing, Church Road, J B Nagar, Andher...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Andheri East</td>\n",
       "      <td>Church Road</td>\n",
       "      <td>400059</td>\n",
       "      <td>19.11167</td>\n",
       "      <td>72.87505</td>\n",
       "      <td>NaN</td>\n",
       "      <td>J B Nagar</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Ramkrishna</td>\n",
       "      <td>here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...</td>\n",
       "      <td>en-GB</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.16653, 'lng': 72.95591}]</td>\n",
       "      <td>5790</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Mulund East</td>\n",
       "      <td>Hutatma Chapekar Bhandu Marg</td>\n",
       "      <td>400081</td>\n",
       "      <td>19.16650</td>\n",
       "      <td>72.95585</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Salvi Wadi</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Skiffle CHS</td>\n",
       "      <td>here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.07813, 'lng': 72.91169}]</td>\n",
       "      <td>6147</td>\n",
       "      <td>[{'id': '900-9300-0221', 'name': 'Residential ...</td>\n",
       "      <td>Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Ghatkopar East</td>\n",
       "      <td>Vallabh Baug Lane</td>\n",
       "      <td>400077</td>\n",
       "      <td>19.07814</td>\n",
       "      <td>72.91175</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Ganash</td>\n",
       "      <td>here:pds:place:356te7vh-c25b431bc219440580a988...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.17182, 'lng': 72.9557}]</td>\n",
       "      <td>6168</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Ganash, Gopal Krishna Gokhale Road, Mulund Eas...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Mulund East</td>\n",
       "      <td>Gopal Krishna Gokhale Road</td>\n",
       "      <td>400081</td>\n",
       "      <td>19.17180</td>\n",
       "      <td>72.95568</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Royal Palms Estate &amp; Properties</td>\n",
       "      <td>here:pds:place:356te7v6-7424bd059ac945ec9d5623...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.16285, 'lng': 72.85787}]</td>\n",
       "      <td>6680</td>\n",
       "      <td>[{'id': '700-7400-0145', 'name': 'Real Estate ...</td>\n",
       "      <td>Royal Palms Estate &amp; Properties, Goregaon East...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Goregaon East</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400063</td>\n",
       "      <td>19.16285</td>\n",
       "      <td>72.85787</td>\n",
       "      <td>[{'phone': [{'value': '+912261462000'}], 'www'...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Sana Guest House</td>\n",
       "      <td>here:pds:place:356te7uc-643359fa033fcf8daed1ed...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.12397, 'lng': 72.84666}]</td>\n",
       "      <td>7069</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Sana Guest House, 68 S V Road, Andheri West, M...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Andheri West</td>\n",
       "      <td>S V Road</td>\n",
       "      <td>400058</td>\n",
       "      <td>19.12396</td>\n",
       "      <td>72.84676</td>\n",
       "      <td>[{'phone': [{'value': '+912232156639'}]}]</td>\n",
       "      <td>NaN</td>\n",
       "      <td>68</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Twinkle Service Apartment</td>\n",
       "      <td>here:pds:place:356te7uc-7c88537101df4ea6a68850...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.14636, 'lng': 72.84589}]</td>\n",
       "      <td>7222</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Twinkle Service Apartment, Oshiwara Garden Roa...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Jogeshwari West</td>\n",
       "      <td>Oshiwara Garden Road</td>\n",
       "      <td>400102</td>\n",
       "      <td>19.14620</td>\n",
       "      <td>72.84590</td>\n",
       "      <td>[{'phone': [{'value': '+919819099019'}], 'www'...</td>\n",
       "      <td>Oshiwara Garden</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Bandy's Riversong</td>\n",
       "      <td>here:pds:place:356te7u9-5649d8369dc442aaa7130b...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.10771, 'lng': 72.84909}]</td>\n",
       "      <td>7322</td>\n",
       "      <td>[{'id': '500-5000-0053', 'name': 'Hotel', 'pri...</td>\n",
       "      <td>Bandy's Riversong, Vile Parle East, Mumbai 400...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Vile Parle East</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400057</td>\n",
       "      <td>19.10781</td>\n",
       "      <td>72.84909</td>\n",
       "      <td>[{'phone': [{'value': '+919820094164'}], 'www'...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Strawberry Vacations</td>\n",
       "      <td>here:pds:place:356te7u9-956d7d7d767748078ab88e...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.09623, 'lng': 72.85419}]</td>\n",
       "      <td>7460</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Strawberry Vacations, Nehru Road, Vile Parle E...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Vile Parle East</td>\n",
       "      <td>Nehru Road</td>\n",
       "      <td>400099</td>\n",
       "      <td>19.09623</td>\n",
       "      <td>72.85419</td>\n",
       "      <td>[{'phone': [{'value': '+919664666457'}], 'www'...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>LOTUS Colony Aarogy Kendra</td>\n",
       "      <td>here:pds:place:356te7u7-3cf7a09df2294d679aa603...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.06424, 'lng': 72.91839}]</td>\n",
       "      <td>7691</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Govandi West</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400043</td>\n",
       "      <td>19.06441</td>\n",
       "      <td>72.91849</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Shivaji Nagar-Lotus Colony</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>La Maison Hospitality</td>\n",
       "      <td>here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.10195, 'lng': 72.84543}]</td>\n",
       "      <td>7937</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>La Maison Hospitality, 1 Parleshwar Marg, Navp...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Vile Parle East</td>\n",
       "      <td>Parleshwar Marg</td>\n",
       "      <td>400057</td>\n",
       "      <td>19.10186</td>\n",
       "      <td>72.84553</td>\n",
       "      <td>[{'phone': [{'value': '+919930122614'}], 'www'...</td>\n",
       "      <td>Navpada</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Oshi</td>\n",
       "      <td>here:pds:place:356te7uc-7a52de251c97490b875666...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.14885, 'lng': 72.83944}]</td>\n",
       "      <td>7956</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Jogeshwari West</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400102</td>\n",
       "      <td>19.14881</td>\n",
       "      <td>72.83934</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Oshiwara</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>BBJ Verona Proposed</td>\n",
       "      <td>here:pds:place:356te7uc-70596e9c0e29441e8897bb...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.14886, 'lng': 72.8389}]</td>\n",
       "      <td>7991</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>BBJ Verona Proposed, Oshiwara, Jogeshwari West...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Mumbai Suburban</td>\n",
       "      <td>Mumbai</td>\n",
       "      <td>Jogeshwari West</td>\n",
       "      <td>NaN</td>\n",
       "      <td>400102</td>\n",
       "      <td>19.14887</td>\n",
       "      <td>72.83901</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Oshiwara</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Bhagat Enterprises</td>\n",
       "      <td>here:pds:place:356te7uu-e5b5ef67de46464d94b444...</td>\n",
       "      <td>en</td>\n",
       "      <td>here:cm:ontology:apartment_rental_flat_rental</td>\n",
       "      <td>place</td>\n",
       "      <td>[{'lat': 19.12502, 'lng': 72.98942}]</td>\n",
       "      <td>8056</td>\n",
       "      <td>[{'id': '700-7200-0324', 'name': 'Apartment/Fl...</td>\n",
       "      <td>Bhagat Enterprises, Gagangiri Maharaj Marg, Se...</td>\n",
       "      <td>IND</td>\n",
       "      <td>...</td>\n",
       "      <td>Thane</td>\n",
       "      <td>Navi Mumbai</td>\n",
       "      <td>Ghansoli</td>\n",
       "      <td>Gagangiri Maharaj Marg</td>\n",
       "      <td>400701</td>\n",
       "      <td>19.12503</td>\n",
       "      <td>72.98947</td>\n",
       "      <td>[{'phone': [{'value': '+919987140408'}]}]</td>\n",
       "      <td>Sector 15</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>20 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                              title  \\\n",
       "0                         Dharamraj   \n",
       "1                 Pajasa Apartments   \n",
       "2                     Scorpio House   \n",
       "3   Andheri East Service Apartments   \n",
       "4                  Aghadi Nagar CHS   \n",
       "5           Irel Officers Apartment   \n",
       "6                    Vic Mon B Wing   \n",
       "7                        Ramkrishna   \n",
       "8                       Skiffle CHS   \n",
       "9                            Ganash   \n",
       "10  Royal Palms Estate & Properties   \n",
       "11                 Sana Guest House   \n",
       "12        Twinkle Service Apartment   \n",
       "13                Bandy's Riversong   \n",
       "14             Strawberry Vacations   \n",
       "15       LOTUS Colony Aarogy Kendra   \n",
       "16            La Maison Hospitality   \n",
       "17                             Oshi   \n",
       "18              BBJ Verona Proposed   \n",
       "19               Bhagat Enterprises   \n",
       "\n",
       "                                                   id language  \\\n",
       "0   here:pds:place:356te7ug-aab7da0959a549568e2d53...       en   \n",
       "1   here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...       en   \n",
       "2   here:pds:place:356te7ug-3fc1a164b55c7471dfef61...       en   \n",
       "3   here:pds:place:356te7uf-0d5db6077151dcd2369691...       en   \n",
       "4   here:pds:place:356te7v5-ea19989e14a440f9b83865...       en   \n",
       "5   here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...       en   \n",
       "6   here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...       en   \n",
       "7   here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...    en-GB   \n",
       "8   here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...       en   \n",
       "9   here:pds:place:356te7vh-c25b431bc219440580a988...       en   \n",
       "10  here:pds:place:356te7v6-7424bd059ac945ec9d5623...       en   \n",
       "11  here:pds:place:356te7uc-643359fa033fcf8daed1ed...       en   \n",
       "12  here:pds:place:356te7uc-7c88537101df4ea6a68850...       en   \n",
       "13  here:pds:place:356te7u9-5649d8369dc442aaa7130b...       en   \n",
       "14  here:pds:place:356te7u9-956d7d7d767748078ab88e...       en   \n",
       "15  here:pds:place:356te7u7-3cf7a09df2294d679aa603...       en   \n",
       "16  here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...       en   \n",
       "17  here:pds:place:356te7uc-7a52de251c97490b875666...       en   \n",
       "18  here:pds:place:356te7uc-70596e9c0e29441e8897bb...       en   \n",
       "19  here:pds:place:356te7uu-e5b5ef67de46464d94b444...       en   \n",
       "\n",
       "                                       ontologyId resultType  \\\n",
       "0   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "1   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "2   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "3   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "4   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "5   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "6   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "7   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "8   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "9   here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "10  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "11  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "12  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "13  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "14  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "15  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "16  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "17  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "18  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "19  here:cm:ontology:apartment_rental_flat_rental      place   \n",
       "\n",
       "                                  access  distance  \\\n",
       "0   [{'lat': 19.12545, 'lng': 72.91935}]      1086   \n",
       "1   [{'lat': 19.12339, 'lng': 72.91275}]      1115   \n",
       "2   [{'lat': 19.11933, 'lng': 72.91227}]      1568   \n",
       "3   [{'lat': 19.11747, 'lng': 72.88374}]      3576   \n",
       "4   [{'lat': 19.16289, 'lng': 72.93287}]      3860   \n",
       "5   [{'lat': 19.09585, 'lng': 72.91369}]      4170   \n",
       "6   [{'lat': 19.11162, 'lng': 72.87512}]      4689   \n",
       "7   [{'lat': 19.16653, 'lng': 72.95591}]      5790   \n",
       "8   [{'lat': 19.07813, 'lng': 72.91169}]      6147   \n",
       "9    [{'lat': 19.17182, 'lng': 72.9557}]      6168   \n",
       "10  [{'lat': 19.16285, 'lng': 72.85787}]      6680   \n",
       "11  [{'lat': 19.12397, 'lng': 72.84666}]      7069   \n",
       "12  [{'lat': 19.14636, 'lng': 72.84589}]      7222   \n",
       "13  [{'lat': 19.10771, 'lng': 72.84909}]      7322   \n",
       "14  [{'lat': 19.09623, 'lng': 72.85419}]      7460   \n",
       "15  [{'lat': 19.06424, 'lng': 72.91839}]      7691   \n",
       "16  [{'lat': 19.10195, 'lng': 72.84543}]      7937   \n",
       "17  [{'lat': 19.14885, 'lng': 72.83944}]      7956   \n",
       "18   [{'lat': 19.14886, 'lng': 72.8389}]      7991   \n",
       "19  [{'lat': 19.12502, 'lng': 72.98942}]      8056   \n",
       "\n",
       "                                           categories  \\\n",
       "0   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "1   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "2   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "3   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "4   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "5   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "6   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "7   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "8   [{'id': '900-9300-0221', 'name': 'Residential ...   \n",
       "9   [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "10  [{'id': '700-7400-0145', 'name': 'Real Estate ...   \n",
       "11  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "12  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "13  [{'id': '500-5000-0053', 'name': 'Hotel', 'pri...   \n",
       "14  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "15  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "16  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "17  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "18  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "19  [{'id': '700-7200-0324', 'name': 'Apartment/Fl...   \n",
       "\n",
       "                                        address.label address.countryCode  \\\n",
       "0   Dharamraj, Hare Krishna Road, Powai, Mumbai 40...                 IND   \n",
       "1   Pajasa Apartments, Central Avenue, Hiranandani...                 IND   \n",
       "2   Scorpio House, Central Avenue, Hiranandani Gar...                 IND   \n",
       "3   Andheri East Service Apartments, Marol, Andher...                 IND   \n",
       "4   Aghadi Nagar CHS, Dargah Road, Bhandup West, M...                 IND   \n",
       "5   Irel Officers Apartment, Damodar Park Road, Da...                 IND   \n",
       "6   Vic Mon B Wing, Church Road, J B Nagar, Andher...                 IND   \n",
       "7   Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...                 IND   \n",
       "8   Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...                 IND   \n",
       "9   Ganash, Gopal Krishna Gokhale Road, Mulund Eas...                 IND   \n",
       "10  Royal Palms Estate & Properties, Goregaon East...                 IND   \n",
       "11  Sana Guest House, 68 S V Road, Andheri West, M...                 IND   \n",
       "12  Twinkle Service Apartment, Oshiwara Garden Roa...                 IND   \n",
       "13  Bandy's Riversong, Vile Parle East, Mumbai 400...                 IND   \n",
       "14  Strawberry Vacations, Nehru Road, Vile Parle E...                 IND   \n",
       "15  LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...                 IND   \n",
       "16  La Maison Hospitality, 1 Parleshwar Marg, Navp...                 IND   \n",
       "17  Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...                 IND   \n",
       "18  BBJ Verona Proposed, Oshiwara, Jogeshwari West...                 IND   \n",
       "19  Bhagat Enterprises, Gagangiri Maharaj Marg, Se...                 IND   \n",
       "\n",
       "    ...   address.county address.city address.district  \\\n",
       "0   ...  Mumbai Suburban       Mumbai            Powai   \n",
       "1   ...  Mumbai Suburban       Mumbai            Powai   \n",
       "2   ...  Mumbai Suburban       Mumbai            Powai   \n",
       "3   ...  Mumbai Suburban       Mumbai     Andheri East   \n",
       "4   ...  Mumbai Suburban       Mumbai     Bhandup West   \n",
       "5   ...  Mumbai Suburban       Mumbai   Ghatkopar West   \n",
       "6   ...  Mumbai Suburban       Mumbai     Andheri East   \n",
       "7   ...  Mumbai Suburban       Mumbai      Mulund East   \n",
       "8   ...  Mumbai Suburban       Mumbai   Ghatkopar East   \n",
       "9   ...  Mumbai Suburban       Mumbai      Mulund East   \n",
       "10  ...  Mumbai Suburban       Mumbai    Goregaon East   \n",
       "11  ...  Mumbai Suburban       Mumbai     Andheri West   \n",
       "12  ...  Mumbai Suburban       Mumbai  Jogeshwari West   \n",
       "13  ...  Mumbai Suburban       Mumbai  Vile Parle East   \n",
       "14  ...  Mumbai Suburban       Mumbai  Vile Parle East   \n",
       "15  ...  Mumbai Suburban       Mumbai     Govandi West   \n",
       "16  ...  Mumbai Suburban       Mumbai  Vile Parle East   \n",
       "17  ...  Mumbai Suburban       Mumbai  Jogeshwari West   \n",
       "18  ...  Mumbai Suburban       Mumbai  Jogeshwari West   \n",
       "19  ...            Thane  Navi Mumbai         Ghansoli   \n",
       "\n",
       "                  address.street address.postalCode position.lat position.lng  \\\n",
       "0              Hare Krishna Road             400076     19.12548     72.91935   \n",
       "1                 Central Avenue             400076     19.12339     72.91274   \n",
       "2                 Central Avenue             400076     19.11933     72.91227   \n",
       "3                            NaN             400059     19.11746     72.88374   \n",
       "4                    Dargah Road             400078     19.16278     72.93287   \n",
       "5              Damodar Park Road             400086     19.09590     72.91356   \n",
       "6                    Church Road             400059     19.11167     72.87505   \n",
       "7   Hutatma Chapekar Bhandu Marg             400081     19.16650     72.95585   \n",
       "8              Vallabh Baug Lane             400077     19.07814     72.91175   \n",
       "9     Gopal Krishna Gokhale Road             400081     19.17180     72.95568   \n",
       "10                           NaN             400063     19.16285     72.85787   \n",
       "11                      S V Road             400058     19.12396     72.84676   \n",
       "12          Oshiwara Garden Road             400102     19.14620     72.84590   \n",
       "13                           NaN             400057     19.10781     72.84909   \n",
       "14                    Nehru Road             400099     19.09623     72.85419   \n",
       "15                           NaN             400043     19.06441     72.91849   \n",
       "16               Parleshwar Marg             400057     19.10186     72.84553   \n",
       "17                           NaN             400102     19.14881     72.83934   \n",
       "18                           NaN             400102     19.14887     72.83901   \n",
       "19        Gagangiri Maharaj Marg             400701     19.12503     72.98947   \n",
       "\n",
       "                                             contacts  \\\n",
       "0                                                 NaN   \n",
       "1   [{'phone': [{'value': '+912269999891'}], 'www'...   \n",
       "2                                                 NaN   \n",
       "3   [{'phone': [{'value': '+919820049408'}], 'www'...   \n",
       "4          [{'mobile': [{'value': '+919324060902'}]}]   \n",
       "5           [{'phone': [{'value': '+912224220843'}]}]   \n",
       "6                                                 NaN   \n",
       "7                                                 NaN   \n",
       "8                                                 NaN   \n",
       "9                                                 NaN   \n",
       "10  [{'phone': [{'value': '+912261462000'}], 'www'...   \n",
       "11          [{'phone': [{'value': '+912232156639'}]}]   \n",
       "12  [{'phone': [{'value': '+919819099019'}], 'www'...   \n",
       "13  [{'phone': [{'value': '+919820094164'}], 'www'...   \n",
       "14  [{'phone': [{'value': '+919664666457'}], 'www'...   \n",
       "15                                                NaN   \n",
       "16  [{'phone': [{'value': '+919930122614'}], 'www'...   \n",
       "17                                                NaN   \n",
       "18                                                NaN   \n",
       "19          [{'phone': [{'value': '+919987140408'}]}]   \n",
       "\n",
       "           address.subdistrict  address.houseNumber  \n",
       "0                          NaN                  NaN  \n",
       "1          Hiranandani Gardens                  NaN  \n",
       "2          Hiranandani Gardens                  NaN  \n",
       "3                        Marol                  NaN  \n",
       "4                          NaN                  NaN  \n",
       "5                 Damodar Park                  NaN  \n",
       "6                    J B Nagar                  NaN  \n",
       "7                   Salvi Wadi                  NaN  \n",
       "8                          NaN                  NaN  \n",
       "9                          NaN                  NaN  \n",
       "10                         NaN                  NaN  \n",
       "11                         NaN                   68  \n",
       "12             Oshiwara Garden                  NaN  \n",
       "13                         NaN                  NaN  \n",
       "14                         NaN                  NaN  \n",
       "15  Shivaji Nagar-Lotus Colony                  NaN  \n",
       "16                     Navpada                    1  \n",
       "17                    Oshiwara                  NaN  \n",
       "18                    Oshiwara                  NaN  \n",
       "19                   Sector 15                  NaN  \n",
       "\n",
       "[20 rows x 23 columns]"
      ]
     },
     "execution_count": 14,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Fetching data form HERE API for IIT Bombay\n",
    "url = 'https://discover.search.hereapi.com/v1/discover?in=circle:19.1334,72.9133;r=10000&q=apartment&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'\n",
    "data = requests.get(url).json()\n",
    "d=json_normalize(data['items'])\n",
    "d.to_csv('api-data/apartment.csv')\n",
    "d"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "6f977ee0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>title</th>\n",
       "      <th>address.label</th>\n",
       "      <th>distance</th>\n",
       "      <th>access</th>\n",
       "      <th>position.lat</th>\n",
       "      <th>position.lng</th>\n",
       "      <th>address.postalCode</th>\n",
       "      <th>contacts</th>\n",
       "      <th>id</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Dharamraj</td>\n",
       "      <td>Dharamraj, Hare Krishna Road, Powai, Mumbai 40...</td>\n",
       "      <td>1086</td>\n",
       "      <td>[{'lat': 19.12545, 'lng': 72.91935}]</td>\n",
       "      <td>19.12548</td>\n",
       "      <td>72.91935</td>\n",
       "      <td>400076</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7ug-aab7da0959a549568e2d53...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Pajasa Apartments</td>\n",
       "      <td>Pajasa Apartments, Central Avenue, Hiranandani...</td>\n",
       "      <td>1115</td>\n",
       "      <td>[{'lat': 19.12339, 'lng': 72.91275}]</td>\n",
       "      <td>19.12339</td>\n",
       "      <td>72.91274</td>\n",
       "      <td>400076</td>\n",
       "      <td>[{'phone': [{'value': '+912269999891'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>Scorpio House</td>\n",
       "      <td>Scorpio House, Central Avenue, Hiranandani Gar...</td>\n",
       "      <td>1568</td>\n",
       "      <td>[{'lat': 19.11933, 'lng': 72.91227}]</td>\n",
       "      <td>19.11933</td>\n",
       "      <td>72.91227</td>\n",
       "      <td>400076</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7ug-3fc1a164b55c7471dfef61...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Andheri East Service Apartments</td>\n",
       "      <td>Andheri East Service Apartments, Marol, Andher...</td>\n",
       "      <td>3576</td>\n",
       "      <td>[{'lat': 19.11747, 'lng': 72.88374}]</td>\n",
       "      <td>19.11746</td>\n",
       "      <td>72.88374</td>\n",
       "      <td>400059</td>\n",
       "      <td>[{'phone': [{'value': '+919820049408'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7uf-0d5db6077151dcd2369691...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Aghadi Nagar CHS</td>\n",
       "      <td>Aghadi Nagar CHS, Dargah Road, Bhandup West, M...</td>\n",
       "      <td>3860</td>\n",
       "      <td>[{'lat': 19.16289, 'lng': 72.93287}]</td>\n",
       "      <td>19.16278</td>\n",
       "      <td>72.93287</td>\n",
       "      <td>400078</td>\n",
       "      <td>[{'mobile': [{'value': '+919324060902'}]}]</td>\n",
       "      <td>here:pds:place:356te7v5-ea19989e14a440f9b83865...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>Irel Officers Apartment</td>\n",
       "      <td>Irel Officers Apartment, Damodar Park Road, Da...</td>\n",
       "      <td>4170</td>\n",
       "      <td>[{'lat': 19.09585, 'lng': 72.91369}]</td>\n",
       "      <td>19.09590</td>\n",
       "      <td>72.91356</td>\n",
       "      <td>400086</td>\n",
       "      <td>[{'phone': [{'value': '+912224220843'}]}]</td>\n",
       "      <td>here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>Vic Mon B Wing</td>\n",
       "      <td>Vic Mon B Wing, Church Road, J B Nagar, Andher...</td>\n",
       "      <td>4689</td>\n",
       "      <td>[{'lat': 19.11162, 'lng': 72.87512}]</td>\n",
       "      <td>19.11167</td>\n",
       "      <td>72.87505</td>\n",
       "      <td>400059</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>Ramkrishna</td>\n",
       "      <td>Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...</td>\n",
       "      <td>5790</td>\n",
       "      <td>[{'lat': 19.16653, 'lng': 72.95591}]</td>\n",
       "      <td>19.16650</td>\n",
       "      <td>72.95585</td>\n",
       "      <td>400081</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>Skiffle CHS</td>\n",
       "      <td>Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...</td>\n",
       "      <td>6147</td>\n",
       "      <td>[{'lat': 19.07813, 'lng': 72.91169}]</td>\n",
       "      <td>19.07814</td>\n",
       "      <td>72.91175</td>\n",
       "      <td>400077</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>Ganash</td>\n",
       "      <td>Ganash, Gopal Krishna Gokhale Road, Mulund Eas...</td>\n",
       "      <td>6168</td>\n",
       "      <td>[{'lat': 19.17182, 'lng': 72.9557}]</td>\n",
       "      <td>19.17180</td>\n",
       "      <td>72.95568</td>\n",
       "      <td>400081</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7vh-c25b431bc219440580a988...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>Royal Palms Estate &amp; Properties</td>\n",
       "      <td>Royal Palms Estate &amp; Properties, Goregaon East...</td>\n",
       "      <td>6680</td>\n",
       "      <td>[{'lat': 19.16285, 'lng': 72.85787}]</td>\n",
       "      <td>19.16285</td>\n",
       "      <td>72.85787</td>\n",
       "      <td>400063</td>\n",
       "      <td>[{'phone': [{'value': '+912261462000'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7v6-7424bd059ac945ec9d5623...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>Sana Guest House</td>\n",
       "      <td>Sana Guest House, 68 S V Road, Andheri West, M...</td>\n",
       "      <td>7069</td>\n",
       "      <td>[{'lat': 19.12397, 'lng': 72.84666}]</td>\n",
       "      <td>19.12396</td>\n",
       "      <td>72.84676</td>\n",
       "      <td>400058</td>\n",
       "      <td>[{'phone': [{'value': '+912232156639'}]}]</td>\n",
       "      <td>here:pds:place:356te7uc-643359fa033fcf8daed1ed...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>Twinkle Service Apartment</td>\n",
       "      <td>Twinkle Service Apartment, Oshiwara Garden Roa...</td>\n",
       "      <td>7222</td>\n",
       "      <td>[{'lat': 19.14636, 'lng': 72.84589}]</td>\n",
       "      <td>19.14620</td>\n",
       "      <td>72.84590</td>\n",
       "      <td>400102</td>\n",
       "      <td>[{'phone': [{'value': '+919819099019'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7uc-7c88537101df4ea6a68850...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>Bandy's Riversong</td>\n",
       "      <td>Bandy's Riversong, Vile Parle East, Mumbai 400...</td>\n",
       "      <td>7322</td>\n",
       "      <td>[{'lat': 19.10771, 'lng': 72.84909}]</td>\n",
       "      <td>19.10781</td>\n",
       "      <td>72.84909</td>\n",
       "      <td>400057</td>\n",
       "      <td>[{'phone': [{'value': '+919820094164'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7u9-5649d8369dc442aaa7130b...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>Strawberry Vacations</td>\n",
       "      <td>Strawberry Vacations, Nehru Road, Vile Parle E...</td>\n",
       "      <td>7460</td>\n",
       "      <td>[{'lat': 19.09623, 'lng': 72.85419}]</td>\n",
       "      <td>19.09623</td>\n",
       "      <td>72.85419</td>\n",
       "      <td>400099</td>\n",
       "      <td>[{'phone': [{'value': '+919664666457'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7u9-956d7d7d767748078ab88e...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>LOTUS Colony Aarogy Kendra</td>\n",
       "      <td>LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...</td>\n",
       "      <td>7691</td>\n",
       "      <td>[{'lat': 19.06424, 'lng': 72.91839}]</td>\n",
       "      <td>19.06441</td>\n",
       "      <td>72.91849</td>\n",
       "      <td>400043</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7u7-3cf7a09df2294d679aa603...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>La Maison Hospitality</td>\n",
       "      <td>La Maison Hospitality, 1 Parleshwar Marg, Navp...</td>\n",
       "      <td>7937</td>\n",
       "      <td>[{'lat': 19.10195, 'lng': 72.84543}]</td>\n",
       "      <td>19.10186</td>\n",
       "      <td>72.84553</td>\n",
       "      <td>400057</td>\n",
       "      <td>[{'phone': [{'value': '+919930122614'}], 'www'...</td>\n",
       "      <td>here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>Oshi</td>\n",
       "      <td>Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...</td>\n",
       "      <td>7956</td>\n",
       "      <td>[{'lat': 19.14885, 'lng': 72.83944}]</td>\n",
       "      <td>19.14881</td>\n",
       "      <td>72.83934</td>\n",
       "      <td>400102</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7uc-7a52de251c97490b875666...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>BBJ Verona Proposed</td>\n",
       "      <td>BBJ Verona Proposed, Oshiwara, Jogeshwari West...</td>\n",
       "      <td>7991</td>\n",
       "      <td>[{'lat': 19.14886, 'lng': 72.8389}]</td>\n",
       "      <td>19.14887</td>\n",
       "      <td>72.83901</td>\n",
       "      <td>400102</td>\n",
       "      <td>NaN</td>\n",
       "      <td>here:pds:place:356te7uc-70596e9c0e29441e8897bb...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>Bhagat Enterprises</td>\n",
       "      <td>Bhagat Enterprises, Gagangiri Maharaj Marg, Se...</td>\n",
       "      <td>8056</td>\n",
       "      <td>[{'lat': 19.12502, 'lng': 72.98942}]</td>\n",
       "      <td>19.12503</td>\n",
       "      <td>72.98947</td>\n",
       "      <td>400701</td>\n",
       "      <td>[{'phone': [{'value': '+919987140408'}]}]</td>\n",
       "      <td>here:pds:place:356te7uu-e5b5ef67de46464d94b444...</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                              title  \\\n",
       "0                         Dharamraj   \n",
       "1                 Pajasa Apartments   \n",
       "2                     Scorpio House   \n",
       "3   Andheri East Service Apartments   \n",
       "4                  Aghadi Nagar CHS   \n",
       "5           Irel Officers Apartment   \n",
       "6                    Vic Mon B Wing   \n",
       "7                        Ramkrishna   \n",
       "8                       Skiffle CHS   \n",
       "9                            Ganash   \n",
       "10  Royal Palms Estate & Properties   \n",
       "11                 Sana Guest House   \n",
       "12        Twinkle Service Apartment   \n",
       "13                Bandy's Riversong   \n",
       "14             Strawberry Vacations   \n",
       "15       LOTUS Colony Aarogy Kendra   \n",
       "16            La Maison Hospitality   \n",
       "17                             Oshi   \n",
       "18              BBJ Verona Proposed   \n",
       "19               Bhagat Enterprises   \n",
       "\n",
       "                                        address.label  distance  \\\n",
       "0   Dharamraj, Hare Krishna Road, Powai, Mumbai 40...      1086   \n",
       "1   Pajasa Apartments, Central Avenue, Hiranandani...      1115   \n",
       "2   Scorpio House, Central Avenue, Hiranandani Gar...      1568   \n",
       "3   Andheri East Service Apartments, Marol, Andher...      3576   \n",
       "4   Aghadi Nagar CHS, Dargah Road, Bhandup West, M...      3860   \n",
       "5   Irel Officers Apartment, Damodar Park Road, Da...      4170   \n",
       "6   Vic Mon B Wing, Church Road, J B Nagar, Andher...      4689   \n",
       "7   Ramkrishna, Hutatma Chapekar Bhandu Marg, Salv...      5790   \n",
       "8   Skiffle CHS, Vallabh Baug Lane, Ghatkopar East...      6147   \n",
       "9   Ganash, Gopal Krishna Gokhale Road, Mulund Eas...      6168   \n",
       "10  Royal Palms Estate & Properties, Goregaon East...      6680   \n",
       "11  Sana Guest House, 68 S V Road, Andheri West, M...      7069   \n",
       "12  Twinkle Service Apartment, Oshiwara Garden Roa...      7222   \n",
       "13  Bandy's Riversong, Vile Parle East, Mumbai 400...      7322   \n",
       "14  Strawberry Vacations, Nehru Road, Vile Parle E...      7460   \n",
       "15  LOTUS Colony Aarogy Kendra, Shivaji Nagar-Lotu...      7691   \n",
       "16  La Maison Hospitality, 1 Parleshwar Marg, Navp...      7937   \n",
       "17  Oshi, Oshiwara, Jogeshwari West, Mumbai 400102...      7956   \n",
       "18  BBJ Verona Proposed, Oshiwara, Jogeshwari West...      7991   \n",
       "19  Bhagat Enterprises, Gagangiri Maharaj Marg, Se...      8056   \n",
       "\n",
       "                                  access  position.lat  position.lng  \\\n",
       "0   [{'lat': 19.12545, 'lng': 72.91935}]      19.12548      72.91935   \n",
       "1   [{'lat': 19.12339, 'lng': 72.91275}]      19.12339      72.91274   \n",
       "2   [{'lat': 19.11933, 'lng': 72.91227}]      19.11933      72.91227   \n",
       "3   [{'lat': 19.11747, 'lng': 72.88374}]      19.11746      72.88374   \n",
       "4   [{'lat': 19.16289, 'lng': 72.93287}]      19.16278      72.93287   \n",
       "5   [{'lat': 19.09585, 'lng': 72.91369}]      19.09590      72.91356   \n",
       "6   [{'lat': 19.11162, 'lng': 72.87512}]      19.11167      72.87505   \n",
       "7   [{'lat': 19.16653, 'lng': 72.95591}]      19.16650      72.95585   \n",
       "8   [{'lat': 19.07813, 'lng': 72.91169}]      19.07814      72.91175   \n",
       "9    [{'lat': 19.17182, 'lng': 72.9557}]      19.17180      72.95568   \n",
       "10  [{'lat': 19.16285, 'lng': 72.85787}]      19.16285      72.85787   \n",
       "11  [{'lat': 19.12397, 'lng': 72.84666}]      19.12396      72.84676   \n",
       "12  [{'lat': 19.14636, 'lng': 72.84589}]      19.14620      72.84590   \n",
       "13  [{'lat': 19.10771, 'lng': 72.84909}]      19.10781      72.84909   \n",
       "14  [{'lat': 19.09623, 'lng': 72.85419}]      19.09623      72.85419   \n",
       "15  [{'lat': 19.06424, 'lng': 72.91839}]      19.06441      72.91849   \n",
       "16  [{'lat': 19.10195, 'lng': 72.84543}]      19.10186      72.84553   \n",
       "17  [{'lat': 19.14885, 'lng': 72.83944}]      19.14881      72.83934   \n",
       "18   [{'lat': 19.14886, 'lng': 72.8389}]      19.14887      72.83901   \n",
       "19  [{'lat': 19.12502, 'lng': 72.98942}]      19.12503      72.98947   \n",
       "\n",
       "   address.postalCode                                           contacts  \\\n",
       "0              400076                                                NaN   \n",
       "1              400076  [{'phone': [{'value': '+912269999891'}], 'www'...   \n",
       "2              400076                                                NaN   \n",
       "3              400059  [{'phone': [{'value': '+919820049408'}], 'www'...   \n",
       "4              400078         [{'mobile': [{'value': '+919324060902'}]}]   \n",
       "5              400086          [{'phone': [{'value': '+912224220843'}]}]   \n",
       "6              400059                                                NaN   \n",
       "7              400081                                                NaN   \n",
       "8              400077                                                NaN   \n",
       "9              400081                                                NaN   \n",
       "10             400063  [{'phone': [{'value': '+912261462000'}], 'www'...   \n",
       "11             400058          [{'phone': [{'value': '+912232156639'}]}]   \n",
       "12             400102  [{'phone': [{'value': '+919819099019'}], 'www'...   \n",
       "13             400057  [{'phone': [{'value': '+919820094164'}], 'www'...   \n",
       "14             400099  [{'phone': [{'value': '+919664666457'}], 'www'...   \n",
       "15             400043                                                NaN   \n",
       "16             400057  [{'phone': [{'value': '+919930122614'}], 'www'...   \n",
       "17             400102                                                NaN   \n",
       "18             400102                                                NaN   \n",
       "19             400701          [{'phone': [{'value': '+919987140408'}]}]   \n",
       "\n",
       "                                                   id  \n",
       "0   here:pds:place:356te7ug-aab7da0959a549568e2d53...  \n",
       "1   here:pds:place:356te7ug-2d6f7d8713484a3c822ff1...  \n",
       "2   here:pds:place:356te7ug-3fc1a164b55c7471dfef61...  \n",
       "3   here:pds:place:356te7uf-0d5db6077151dcd2369691...  \n",
       "4   here:pds:place:356te7v5-ea19989e14a440f9b83865...  \n",
       "5   here:pds:place:356te7ue-e65c876ed64c4bcd89ce87...  \n",
       "6   here:pds:place:356te7ud-e1d26697d0d54f3eb62c7e...  \n",
       "7   here:pds:place:356te7vh-7a6a646cb9f14688aae4bc...  \n",
       "8   here:pds:place:356te7ue-44bc5a50b70e4079ba6ba5...  \n",
       "9   here:pds:place:356te7vh-c25b431bc219440580a988...  \n",
       "10  here:pds:place:356te7v6-7424bd059ac945ec9d5623...  \n",
       "11  here:pds:place:356te7uc-643359fa033fcf8daed1ed...  \n",
       "12  here:pds:place:356te7uc-7c88537101df4ea6a68850...  \n",
       "13  here:pds:place:356te7u9-5649d8369dc442aaa7130b...  \n",
       "14  here:pds:place:356te7u9-956d7d7d767748078ab88e...  \n",
       "15  here:pds:place:356te7u7-3cf7a09df2294d679aa603...  \n",
       "16  here:pds:place:356te7u9-d7b0a51c06674bbebbb9cb...  \n",
       "17  here:pds:place:356te7uc-7a52de251c97490b875666...  \n",
       "18  here:pds:place:356te7uc-70596e9c0e29441e8897bb...  \n",
       "19  here:pds:place:356te7uu-e5b5ef67de46464d94b444...  "
      ]
     },
     "execution_count": 15,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Cleaning API data\n",
    "d2=d[['title','address.label','distance','access','position.lat','position.lng','address.postalCode','contacts','id']]\n",
    "d2.to_csv('api-data/cleaned_apartment.csv')\n",
    "d2"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "19391523",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>position.lat</th>\n",
       "      <th>position.lng</th>\n",
       "      <th>Cafes</th>\n",
       "      <th>Restaurents</th>\n",
       "      <th>Gyms</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>19.12548</td>\n",
       "      <td>72.91935</td>\n",
       "      <td>11</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>19.12339</td>\n",
       "      <td>72.91274</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>19.11933</td>\n",
       "      <td>72.91227</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>19.11746</td>\n",
       "      <td>72.88374</td>\n",
       "      <td>8</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>19.16278</td>\n",
       "      <td>72.93287</td>\n",
       "      <td>4</td>\n",
       "      <td>20</td>\n",
       "      <td>7</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>19.09590</td>\n",
       "      <td>72.91356</td>\n",
       "      <td>16</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>19.11167</td>\n",
       "      <td>72.87505</td>\n",
       "      <td>15</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>19.16650</td>\n",
       "      <td>72.95585</td>\n",
       "      <td>6</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>19.07814</td>\n",
       "      <td>72.91175</td>\n",
       "      <td>15</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>19.17180</td>\n",
       "      <td>72.95568</td>\n",
       "      <td>7</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>19.16285</td>\n",
       "      <td>72.85787</td>\n",
       "      <td>7</td>\n",
       "      <td>20</td>\n",
       "      <td>15</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>19.12396</td>\n",
       "      <td>72.84676</td>\n",
       "      <td>10</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>19.14620</td>\n",
       "      <td>72.84590</td>\n",
       "      <td>4</td>\n",
       "      <td>20</td>\n",
       "      <td>9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>19.10781</td>\n",
       "      <td>72.84909</td>\n",
       "      <td>18</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>19.09623</td>\n",
       "      <td>72.85419</td>\n",
       "      <td>16</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>19.06441</td>\n",
       "      <td>72.91849</td>\n",
       "      <td>1</td>\n",
       "      <td>20</td>\n",
       "      <td>13</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>19.10186</td>\n",
       "      <td>72.84553</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>19.14881</td>\n",
       "      <td>72.83934</td>\n",
       "      <td>17</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>19.14887</td>\n",
       "      <td>72.83901</td>\n",
       "      <td>18</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>19.12503</td>\n",
       "      <td>72.98947</td>\n",
       "      <td>1</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    position.lat  position.lng  Cafes  Restaurents  Gyms\n",
       "0       19.12548      72.91935     11           20    18\n",
       "1       19.12339      72.91274     20           20    20\n",
       "2       19.11933      72.91227     20           20    20\n",
       "3       19.11746      72.88374      8           20    20\n",
       "4       19.16278      72.93287      4           20     7\n",
       "5       19.09590      72.91356     16           20    18\n",
       "6       19.11167      72.87505     15           20    20\n",
       "7       19.16650      72.95585      6           20    20\n",
       "8       19.07814      72.91175     15           20    20\n",
       "9       19.17180      72.95568      7           20    20\n",
       "10      19.16285      72.85787      7           20    15\n",
       "11      19.12396      72.84676     10           20    20\n",
       "12      19.14620      72.84590      4           20     9\n",
       "13      19.10781      72.84909     18           20    20\n",
       "14      19.09623      72.85419     16           20    18\n",
       "15      19.06441      72.91849      1           20    13\n",
       "16      19.10186      72.84553     20           20    20\n",
       "17      19.14881      72.83934     17           20    20\n",
       "18      19.14887      72.83901     18           20    20\n",
       "19      19.12503      72.98947      1           20     2"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Counting no. of cafes, department stores and gyms near apartments around IIT Bombay\n",
    "df_final=d2[['position.lat','position.lng']]\n",
    "\n",
    "CafeList=[]\n",
    "ResList=[]\n",
    "GymList=[]\n",
    "latitudes = list(d2['position.lat'])\n",
    "longitudes = list( d2['position.lng'])\n",
    "for lat, lng in zip(latitudes, longitudes):    \n",
    "    radius = '1000' #Set the radius to 1000 metres\n",
    "    latitude=lat\n",
    "    longitude=lng\n",
    "    \n",
    "    search_query = 'cafe' #Search for any cafes\n",
    "    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)\n",
    "    results = requests.get(url).json()\n",
    "    venues=json_normalize(results['items'])\n",
    "    CafeList.append(venues['title'].count())\n",
    "\t\n",
    "    search_query = 'gym' #Search for any gyms\n",
    "    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)\n",
    "    results = requests.get(url).json()\n",
    "    venues=json_normalize(results['items'])\n",
    "    GymList.append(venues['title'].count())\n",
    "\n",
    "    search_query = 'restaurents' #search for supermarkets\n",
    "    url = 'https://discover.search.hereapi.com/v1/discover?in=circle:{},{};r={}&q={}&apiKey=uJHMEjeagmFGldXp661-pDMf4R-PxvWIu7I68UjYC5Q'.format(latitude, longitude, radius, search_query)\n",
    "    results = requests.get(url).json()\n",
    "    venues=json_normalize(results['items'])\n",
    "    ResList.append(venues['title'].count())\n",
    "\n",
    "df_final['Cafes'] = CafeList\n",
    "df_final['Restaurents'] = ResList\n",
    "df_final['Gyms'] = GymList\n",
    "\n",
    "df_final"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "54165f04",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>position.lat</th>\n",
       "      <th>position.lng</th>\n",
       "      <th>Cafes</th>\n",
       "      <th>Restaurents</th>\n",
       "      <th>Gyms</th>\n",
       "      <th>Cluster</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>19.12548</td>\n",
       "      <td>72.91935</td>\n",
       "      <td>11</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>19.12339</td>\n",
       "      <td>72.91274</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>19.11933</td>\n",
       "      <td>72.91227</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>19.11746</td>\n",
       "      <td>72.88374</td>\n",
       "      <td>8</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>19.16278</td>\n",
       "      <td>72.93287</td>\n",
       "      <td>4</td>\n",
       "      <td>20</td>\n",
       "      <td>7</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>19.09590</td>\n",
       "      <td>72.91356</td>\n",
       "      <td>16</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>19.11167</td>\n",
       "      <td>72.87505</td>\n",
       "      <td>15</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>19.16650</td>\n",
       "      <td>72.95585</td>\n",
       "      <td>6</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>19.07814</td>\n",
       "      <td>72.91175</td>\n",
       "      <td>15</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>19.17180</td>\n",
       "      <td>72.95568</td>\n",
       "      <td>7</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>19.16285</td>\n",
       "      <td>72.85787</td>\n",
       "      <td>7</td>\n",
       "      <td>20</td>\n",
       "      <td>15</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>19.12396</td>\n",
       "      <td>72.84676</td>\n",
       "      <td>10</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>19.14620</td>\n",
       "      <td>72.84590</td>\n",
       "      <td>4</td>\n",
       "      <td>20</td>\n",
       "      <td>9</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>19.10781</td>\n",
       "      <td>72.84909</td>\n",
       "      <td>18</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>19.09623</td>\n",
       "      <td>72.85419</td>\n",
       "      <td>16</td>\n",
       "      <td>20</td>\n",
       "      <td>18</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>19.06441</td>\n",
       "      <td>72.91849</td>\n",
       "      <td>1</td>\n",
       "      <td>20</td>\n",
       "      <td>13</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>19.10186</td>\n",
       "      <td>72.84553</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>19.14881</td>\n",
       "      <td>72.83934</td>\n",
       "      <td>17</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>19.14887</td>\n",
       "      <td>72.83901</td>\n",
       "      <td>18</td>\n",
       "      <td>20</td>\n",
       "      <td>20</td>\n",
       "      <td>1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>19.12503</td>\n",
       "      <td>72.98947</td>\n",
       "      <td>1</td>\n",
       "      <td>20</td>\n",
       "      <td>2</td>\n",
       "      <td>0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    position.lat  position.lng  Cafes  Restaurents  Gyms Cluster\n",
       "0       19.12548      72.91935     11           20    18       2\n",
       "1       19.12339      72.91274     20           20    20       1\n",
       "2       19.11933      72.91227     20           20    20       1\n",
       "3       19.11746      72.88374      8           20    20       2\n",
       "4       19.16278      72.93287      4           20     7       0\n",
       "5       19.09590      72.91356     16           20    18       1\n",
       "6       19.11167      72.87505     15           20    20       1\n",
       "7       19.16650      72.95585      6           20    20       2\n",
       "8       19.07814      72.91175     15           20    20       1\n",
       "9       19.17180      72.95568      7           20    20       2\n",
       "10      19.16285      72.85787      7           20    15       2\n",
       "11      19.12396      72.84676     10           20    20       2\n",
       "12      19.14620      72.84590      4           20     9       0\n",
       "13      19.10781      72.84909     18           20    20       1\n",
       "14      19.09623      72.85419     16           20    18       1\n",
       "15      19.06441      72.91849      1           20    13       0\n",
       "16      19.10186      72.84553     20           20    20       1\n",
       "17      19.14881      72.83934     17           20    20       1\n",
       "18      19.14887      72.83901     18           20    20       1\n",
       "19      19.12503      72.98947      1           20     2       0"
      ]
     },
     "execution_count": 20,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Run K-means clustering on dataframe\n",
    "kclusters = 3\n",
    "\n",
    "kmeans = KMeans(n_clusters=kclusters, random_state=0).fit(df_final)\n",
    "df_final['Cluster']=kmeans.labels_\n",
    "df_final['Cluster']=df_final['Cluster'].apply(str)\n",
    "df_final"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "d90e7389",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<folium.map.Marker at 0x20e3d5dd850>"
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Plotting clustered locations on map using Folium\n",
    "\n",
    "#define coordinates of the college\n",
    "map_bom=folium.Map(location=[19.1334,72.9133],zoom_start=12)\n",
    "\n",
    "# instantiate a feature group for the incidents in the dataframe\n",
    "locations = folium.map.FeatureGroup()\n",
    "\n",
    "# set color scheme for the clusters\n",
    "def color_producer(cluster):\n",
    "    if cluster=='0':\n",
    "        return 'green'\n",
    "    elif cluster=='1':\n",
    "        return 'orange'\n",
    "    else:\n",
    "        return 'red'\n",
    "\n",
    "latitudes = list(df_final['position.lat'])\n",
    "longitudes = list(df_final['position.lng'])\n",
    "labels = list(df_final['Cluster'])\n",
    "names=list(d2['title'])\n",
    "for lat, lng, label,names in zip(latitudes, longitudes, labels,names):\n",
    "    folium.CircleMarker(\n",
    "            [lat,lng],\n",
    "            fill=True,\n",
    "            fill_opacity=1,\n",
    "            popup=folium.Popup(names, max_width = 300),\n",
    "            radius=5,\n",
    "            color=color_producer(label)\n",
    "        ).add_to(map_bom)\n",
    "\n",
    "# add locations to map\n",
    "map_bom.add_child(locations)\n",
    "folium.Marker([19.1334,72.9133],popup='IIT Bombay').add_to(map_bom)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "f6b72946",
   "metadata": {},
   "outputs": [],
   "source": [
    "#saving the map \n",
    "map_bom.save(\"map-IITBombay.html\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aea0f266",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e1376f07",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
